export const rawData = [
  {
    product: "HPE EL8000 5U CTO Front Cabling Chassis",
    order: 10001,
    price: 64950,
    shipped: true,
    month: "June",
    status: "Pricing",
  },
  {
    product: "Hawkeye III Lite",
    order: 10002,
    price: 33850,
    shipped: false,
    month: "October",
    status: "Pricing",
  },
  {
    product: "Expeditionary Networking and Compute Platform",
    order: 10003,
    price: 29600,
    shipped: false,
    month: "August",
    status: "New",
  },
  {
    product: "Dell Latitude 5430 Rugged",
    order: 10004,
    price: 48890,
    shipped: true,
    month: "February",
    status: "Complete",
  },
  {
    product: "AC Power Supply, Outdoor, 120W, Switchcraft",
    order: 10005,
    price: 15774,
    shipped: false,
    month: "January",
    status: "Complete",
  },
  {
    product: "2TB SSD Hard Drive",
    order: 10006,
    price: 18460,
    shipped: false,
    month: "July",
    status: "New",
  },
  {
    product: "128 GB RAM",
    order: 10007,
    price: 33795,
    shipped: true,
    month: "September",
    status: "Proposal Submitted",
  },
  {
    product: "Dell Latitude 5430 Rugged",
    order: 10008,
    price: 175720,
    shipped: false,
    month: "December",
    status: "Proposal Submitted",
  },
  {
    product: "2TB SSD Hard Drive",
    order: 10009,
    price: 25795,
    shipped: false,
    month: "April",
    status: "Proposal Submitted",
  },
  {
    product: "AC Power Supply, Outdoor, 120W, Switchcraft",
    order: 10010,
    price: 13724,
    shipped: false,
    month: "November",
    status: "New",
  },
  {
    product: "16GB RAM",
    order: 10011,
    price: 69425,
    shipped: true,
    month: "May",
    status: "Invoicing",
  },
  {
    product: "HPE EL8000 5U CTO Front Cabling Chassis",
    order: 10012,
    price: 64950,
    shipped: true,
    month: "June",
    status: "Invoicing",
  },
  {
    product: "Hawkeye III Lite",
    order: 10013,
    price: 33850,
    shipped: false,
    month: "October",
    status: "New",
  },
  {
    product: "Expeditionary Networking and Compute Platform",
    order: 10014,
    price: 29600,
    shipped: false,
    month: "August",
    status: "Invoicing",
  },
  {
    product: "Dell Latitude 5430 Rugged",
    order: 10015,
    price: 48890,
    shipped: true,
    month: "February",
    status: "New",
  },
  {
    product: "AC Power Supply, Outdoor, 120W, Switchcraft",
    order: 10016,
    price: 15774,
    shipped: false,
    month: "January",
    status: "Complete",
  },
  {
    product: "2TB SSD Hard Drive",
    order: 10017,
    price: 18460,
    shipped: false,
    month: "July",
    status: "Awarded",
  },
  {
    product: "128 GB RAM",
    order: 10018,
    price: 33795,
    shipped: true,
    month: "September",
    status: "Awarded",
  },
  {
    product: "Dell Latitude 5430 Rugged",
    order: 10019,
    price: 175720,
    shipped: false,
    month: "December",
    status: "New",
  },
  {
    product: "2TB SSD Hard Drive",
    order: 10020,
    price: 25795,
    shipped: false,
    month: "April",
    status: "New",
  },
  {
    product: "AC Power Supply, Outdoor, 120W, Switchcraft",
    order: 10021,
    price: 13724,
    shipped: false,
    month: "November",
    status: "PCA Review",
  },
  {
    product: "16GB RAM",
    order: 10022,
    price: 69425,
    shipped: true,
    month: "May",
    status: "PCA Review",
  },
  {
    product: "HPE EL8000 5U CTO Front Cabling Chassis",
    order: 10023,
    price: 64950,
    shipped: true,
    month: "June",
    status: "New",
  },
  {
    product: "Hawkeye III Lite",
    order: 10024,
    price: 33850,
    shipped: false,
    month: "October",
    status: "New",
  },
  {
    product: "Expeditionary Networking and Compute Platform",
    order: 10025,
    price: 29600,
    shipped: false,
    month: "August",
    status: "Awaiting Funding",
  },
  {
    product: "Dell Latitude 5430 Rugged",
    order: 10026,
    price: 48890,
    shipped: true,
    month: "February",
    status: "New",
  },
  {
    product: "AC Power Supply, Outdoor, 120W, Switchcraft",
    order: 10027,
    price: 15774,
    shipped: false,
    month: "January",
    status: "Pricing",
  },
  {
    product: "2TB SSD Hard Drive",
    order: 10028,
    price: 18460,
    shipped: false,
    month: "July",
    status: "New",
  },
  {
    product: "128 GB RAM",
    order: 10029,
    price: 33795,
    shipped: true,
    month: "September",
    status: "Pricing",
  },
  {
    product: "Dell Latitude 5430 Rugged",
    order: 10030,
    price: 175720,
    shipped: false,
    month: "December",
    status: "Pricing Approved",
  },
  {
    product: "2TB SSD Hard Drive",
    order: 10031,
    price: 25795,
    shipped: false,
    month: "April",
    status: "Awarded",
  },
  {
    product: "AC Power Supply, Outdoor, 120W, Switchcraft",
    order: 10032,
    price: 13724,
    shipped: false,
    month: "November",
    status: "Bid",
  },
  {
    product: "16GB RAM",
    order: 10033,
    price: 69425,
    shipped: true,
    month: "May",
    status: "Complete",
  },
];

export const rawCols = [
  {
    field: "product",
    editable: true,
    cellEditor: "agSelectCellEditor",
    cellEditorParams: {
      values: [
        "HPE EL8000 5U CTO Front Cabling Chassis",
        "Hawkeye III Lite",
        "Expeditionary Networking and Compute Platform",
        "Dell Latitude 5430 Rugged",
        "AC Power Supply, Outdoor, 120W, Switchcraft",
        "2TB SSD Hard Drive",
        "128 GB RAM",
        "16GB RAM",
      ],
    },
  },
  {
    field: "status",
    editable: true,
    cellEditor: "agSelectCellEditor",
    cellEditorParams: {
      values: [
        "New",
        "Awaiting Funding",
        "Review",
        "Bid",
        "No Bid",
        "Pricing",
        "PCA Review",
        "Pricing Approved",
        "Proposal Submitted",
        "Awarded",
        "Invoicing",
        "Complete",
      ],
    },
  },
  { field: "shipped" },
  { field: "order", filter: "agNumberColumnFilter" },
  { field: "price", filter: "agNumberColumnFilter" },
  {
    field: "month",
    comparator: (valueA, valueB) => {
      const months = [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
      ];
      const idxA = months.indexOf(valueA);
      const idxB = months.indexOf(valueB);
      return idxA - idxB;
    },
  },
];
